services:
  event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher
    public: true
  configuration:
    class: EclipseGc\SiteSync\Configuration
    factory: ['\EclipseGc\SiteSync\Configuration', getFromFile]
    public: true
  sitesync.dispatcher:
    class: EclipseGc\SiteSync\Dispatcher
    arguments: ['@event_dispatcher', '@configuration']
    public: true
  sitesync.subscriber.type.drupal8:
    class: EclipseGc\SiteSync\EventSubscriber\Type\Drupal8
    arguments: ['@service_container']
    public: true
    tags:
        - { name: kernel.event_subscriber }
  sitesync.type.drupal8:
    class: EclipseGc\SiteSync\Type\Drupal8
    arguments: ['@sitesync.dispatcher']
    public: true
  sitesync.subscriber.source.aegir:
    class: EclipseGc\SiteSync\EventSubscriber\Source\Aegir
    arguments: ['@service_container']
    public: true
    tags:
      - { name: kernel.event_subscriber }
  sitesync.source.aegir:
    class: EclipseGc\SiteSync\Source\Aegir
    arguments: ['@sitesync.dispatcher']
    public: true
  sitesync.subscriber.source.drupal:
    class: EclipseGc\SiteSync\EventSubscriber\Source\DrupalSsh
    arguments: ['@service_container']
    public: true
    tags:
      - { name: kernel.event_subscriber }
  sitesync.source.drupalssh:
    class: EclipseGc\SiteSync\Source\Drupal
    arguments: ['@sitesync.dispatcher']
    public: true
  sitesync.subscriber.environment.ddev:
    class: EclipseGc\SiteSync\EventSubscriber\Environment\Ddev
    public: true;
    tags:
      - { name: kernel.event_subscriber }
  sitesync.command.init:
    class: EclipseGc\SiteSync\Command\Initialize
    arguments: [null, '@sitesync.dispatcher']
    public: true
  sitesync.command.pull:
    class: EclipseGc\SiteSync\Command\Pull
    arguments: [null, '@sitesync.dispatcher']
    public: true
  sitesync.command.pulldb:
    class: EclipseGc\SiteSync\Command\PullDb
    arguments: [null, '@event_dispatcher']
    public: true
